services:
  dind:
    privileged: true
    build:
      context: dind
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - dind-settings:/var/lib/docker/
    command:
      - --insecure-registry=registry:5000

  registry:
    image: registry:2
    ports:
      - "5050:5000"

    volumes:
        - registry-data:/var/lib/registry
volumes:
    docker-certs-ca:
    docker-certs-client:
    dind-settings:
    registry-data: