services:
  dind:
    privileged: true
    build:
      context: dind

    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - dind-settings:/var/lib/docker/

volumes:
    docker-certs-ca:
    docker-certs-client:
    dind-settings: