services:
  deployment:
    privileged: true
    build:
      context: deployment
    volumes:
        - ./deployment:/app
        - docker-certs-ca:/certs/ca
        - docker-certs-client:/certs/client
    ports:
      - "8000:8000"
      - "4000:4000"
    command:
      - --insecure-registry=${DOCKER_REGISTRY_URL}

  dind:
    env_file:
        - ./dind/.env
    privileged: true
    build:
      context: .
      dockerfile: dind/Dockerfile
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - ./dev:/app
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - dind-settings:/var/lib/docker/
    command:
      - --insecure-registry=${DOCKER_REGISTRY_URL}

  registry:
    image: registry:2
    ports:
      - "5050:5000"

    volumes:
        - registry-data:/var/lib/registry

  testing:
    build:
        context: testing
    tty: true
    volumes:
      - ./testing:/app


volumes:
    docker-certs-ca:
    docker-certs-client:
    dind-settings:
    registry-data: