volumes:
  docker-certs-ca:
  docker-certs-client:
  dind-settings:
  registry-data:

services:

  dind:
    env_file:
        - ./dind/.env
    privileged: true
    build:
      context: .
      dockerfile: dind/Dockerfile
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - ./dev:/app
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - dind-settings:/var/lib/docker/
    command:
      - --insecure-registry=${DOCKER_REGISTRY_URL}

  registry:
    image: registry:2
    ports:
      - "5050:5000"
    volumes:
      - registry-data:/var/lib/registry

  deployment:
    privileged: true
    env_file:
      - ./secret-service/.deployment
    environment:
      DOCKER_TLS_CERTDIR: /certs
    build:
      context: .
      dockerfile: deployment/Dockerfile
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
    expose:
      - 80
    command:
      - --insecure-registry=${DOCKER_REGISTRY_URL}
    labels:
      - "traefik.http.routers.deployment.entrypoints=web"
      - |
        traefik.http.routers.deployment.rule=
        Host(`app.localhost`) ||
        Host(`read-backend.localhost`) ||
        Host(`write-backend.localhost`)
