services:
  frontend:
    build:
      context: frontend
      target: dev
    env_file:
      - ./frontend/.env
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  read-backend:
    build:
      context: python-read
    env_file:
      - ./python-read/.env
    ports:
      - "8000:8000"
    volumes:
      - ./python-read:/app

  write-backend:
    build:
      context: python-write
    env_file:
      - ./python-write/.env
    ports:
      - "8008:8000"
    volumes:
      - ./python-write:/app

  redis:
    volumes:
      - redis-data:/data

volumes:
  redis-data: