services:
  frontend:
    build:
      context: ./frontend
      target: prod
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"

  read-backend:
    build:
      context: ./python-read
    env_file:
      - ./python-read/.env
    ports:
      - "8000:8000"

  write-backend:
    build:
      context: ./python-write
    env_file:
      - ./python-write/.env
    ports:
      - "8008:8000"