services:
  frontend:
    env_file:
      - ./frontend/.env
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app

  read-backend:
    env_file:
      - ./python-read/.env
    ports:
      - "8000:8000"

  write-backend:
    env_file:
      - ./python-write/.env
    ports:
      - "8008:8000"

  redis:
    volumes:
      - redis-data:/data

volumes:
  redis-data: