services:
  frontend:
    build:
      context: frontend
    depends_on:
      - read-backend
      - write-backend

  read-backend:
    build:
      context: python-read
    depends_on:
      redis:
        condition: service_healthy

  write-backend:
    build:
      context: python-write
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 1s
      retries: 3
