services:
  read-backend:
    build:
      context: python-read
    ports:
      - "8000:8000"

  write-backend:
    build:
      context: python-write
    ports:
      - "8008:8000"

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

volumes:
    redis-data: