services:
  python-app:
    build:
      context: pyapp
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    volumes:
        - postgres:/var/lib/postgresql/data

    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5


volumes:
  postgres: